name: Scrape pages

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      SITEMAP_URL: ${{ secrets.SITEMAP_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: Wandalen/wretry.action@master
        with:
          action: actions/setup-java@v4
          with: |
            java-version: '17'
            distribution: 'adopt'
          attempt_limit: 3
          attempt_delay: 120000

      - name: Build with Maven
        uses: Wandalen/wretry.action@master
        with:
          command: mvn -B package --file pom.xml -DskipTests
          attempt_limit: 3
          attempt_delay: 120000

      - name: Run Application
        uses: Wandalen/wretry.action@master
        with:
          command: java -jar target/whole-website-scraper-0.0.1.jar
          attempt_limit: 3
          attempt_delay: 120000